// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTorrent(arg1) {
  return window['go']['torrentclient']['TorrentClient']['AddTorrent'](arg1);
}

export function GenerateAggregateReport() {
  return window['go']['torrentclient']['TorrentClient']['GenerateAggregateReport']();
}

export function LaunchRoutines() {
  return window['go']['torrentclient']['TorrentClient']['LaunchRoutines']();
}
