// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {torrentclient} from '../models';

export function AddTorrent(arg1:string):Promise<void>;

export function GenerateAggregateReport():Promise<torrentclient.AggregateReport>;

export function LaunchRoutines():Promise<void>;
